manifest:
  remotes:
    - name: zmk-keyboards-clawsome
      url-base: https://github.com/BobKaLonger/zmk-keyboards-clawsome
  projects:
    - name: clawsome-coupe
      remote: zmk-keyboards-clawsome
      import: west.yml